### ISSUE TITLE
[Task] PowerBI create first version of report

### ISSUE THREAD

**Issue by jmargutt** [rodekruis/social-media-listening#101]
Based on #87 

- [ ] test [power BI V2 ](https://app.powerbi.com/groups/1e24e23a-6105-4743-82ec-c9c9383b0750/reports/0704671a-ce10-488f-9542-754c81cd9f79/ReportSection12928a9841339145a248?experience=power-bi)
- [ ] @p-phung to add at least a second data set (see in comments)

**Comment by Stef510** [comment]
How this is going @jmargutt ?

**Comment by Stef510** [comment]
@Wessel93 let's organize a meeting to check status of this task, requirements etc as suggested by Phouc
