### ISSUE TITLE
[Deliverables] S25 LAST!

### ISSUE THREAD

**Issue by Stef510** [rodekruis/social-media-listening#108]
What needs to be done?
Request Data : WF and Messages through the [SML app](https://social-media-monitoring.azurewebsites.net/) ->30min max in total (Lakchih)

- [x] Bulgaria
- [x]  Moldova
- [x]  Poland
- [x]  Romania
- [x]  Ukraine
- [x]  Slovakia
- [x]  Hungary

Import Data on Excel file: Duplicate & clean previous FS, WF & WIP + import WF & Messages -> 1h30 max in total for Lakchih

- [x] Bulgaria
- [x]  Moldova
- [x]  Poland
- [x]  Romania
- [x]  Ukraine
- [x]  Slovakia
- [x]  Hungary

Messages: read and cluster 2000 messages in WIP (1h = 500 messages, 4h total per country per person) _** Before to start reading, check previous scrape notes/reports and see if there's any special request from client _** If translation did not work ask Jacopo to fix it -> no more google sheet
 

- [x] Hungary
- [x]  Bulgaria
- [x]  Ukraine
- [x]  Slovakia
- [x]  Poland
- [x]  Romania
- [x]  Moldova

Factsheet: copy and past the compelling insights/quotes and translated them in questions (1h30 per country)
 
- [x] Hungary
- [x]  Bulgaria
- [x]  Ukraine
- [x]  Slovakia
- [x]  Poland
- [x]  Romania
- [x]  Moldova

Add anomalies in monthly anomalies report

Report: narrative of the Factsheet. Note point of interest, action to be taken by client and/or 510 (1h/1h30 per country) -> Laktchih & Ekaterina together

- [x] Hungary
- [x]  Bulgaria
- [x]  Ukraine
- [x]  Slovakia
- [x]  Poland
- [x]  Romania
- [x]  Moldova

Deliverables (Stef)

- [ ] Wrap up deliverables
- [ ] Send to clients 
- [ ] Teams updates

**Comment by EKlochkova** [comment]
- Bulgaria S22 | Present:  Diana Medina. Polina Hristova. No questions/comments.
- Ukraine S25 | Present:  Diana Medina. Yuliya Khrush. Miroslava Negoda. Tetyana Palka. Elizaveta Gorbanenko. OPR904 InfoCenter. No questions/comments.
- Slovakia S25 | Present: Diana Medina. No questions/comments.
- Poland S25 | Present: Bayan Dushaq. No questions/comments.
- Romania S25 | Present: Diana Medina. Iryna Sobol. Iryna told us they have started 2 programs: cash for house and winter program. The programs will run until February 2024, so they asked us to keep an eye on messages/complaints for registration from people about these 2 programs.
- Moldova S23 | Present: Diana Medina. Valentina Harovschi. Bayan Dushaq. Valentina asked to scrape Viber, not only Telegram. She has already sent Viber groups to Diana Medina.
