### ISSUE TITLE
[Feature] Adjust Narrative Report Template

### ISSUE THREAD

**Issue by Wessel93** [rodekruis/social-media-listening#118]
**Describe the solution you'd like**
Create an easy to work with template for the narrative report that will be delivered every month. The report should take over the FAQ function from the former excel report and should facilitate the process of making it (i.e. a table to easily insert questions and quotes as support)

**Comment by EKlochkova** [comment]
https://rodekruis.sharepoint.com/sites/SmlVK-510/Gedeelde%20documenten/Forms/AllItems.aspx?id=%2Fsites%2FSmlVK%2D510%2FGedeelde%20documenten%2FSML%20%2D%20Ukraine%20Emergency%20Appeal%2FSML%20TEMPLATES%2FSML%20FAQ%20TEMPLATE%2Epdf&viewid=f57b9f70%2D4f57%2D47f9%2D9896%2Da95b97b4c499&parent=%2Fsites%2FSmlVK%2D510%2FGedeelde%20documenten%2FSML%20%2D%20Ukraine%20Emergency%20Appeal%2FSML%20TEMPLATES

**Comment by Wessel93** [comment]
Done
