### ISSUE TITLE
[Smaal ticket] Add trend Visualizations to dashboard

### ISSUE THREAD

**Issue by Wessel93** [rodekruis/social-media-listening#124]
- [x] # members in a group over time
- [x] # messages per group over time
- [x] # messages per topic
- [x] Can we show difference with last month in bar charts showing number of messages per topic?

**Comment by p-phung** [comment]
Implemented. A few points to pay attentions, mostly related to the limited data we have:
- Highlight is the the calculation of classifying "latest month" and "previous month" based on the date labels of the data. The former is when the difference between the current month and the data is 1 (or -11 for January-looked-into-December case), the latter 2 (or -10 for January-looked-into-November). When the difference is 0, the data is classified as "Processing" as it is being processed.
- The Country Report page is set to filter only data classified as "Latest". At the time of writing it is in Jan, the same for the data, this filter can't be tested yet.
- In the Trend page, user and messages visuals are also based on the calculation above. On top of that, the visuals are time-series. As we only have one month data, this is not possible yet to completely test it.

--> Park here for team to review and discuss if we can pick up another round for testing and revising when Feb data is added
