### ISSUE TITLE
[Spike] Can we create word frequencies in PowerBi?

### ISSUE THREAD

**Issue by Wessel93** [rodekruis/social-media-listening#126]
- [ ] Develop M-code/measure to get word frequencies over all messages

**Comment by jmargutt** [comment]
So after 2h of research I concluded that:
- Counting words in PowerBI is possible, but CLEANING the text - removing punctuations and emojis, splitting sentences in words - is a holy mess
-  Therefore, let's park it for now

**Comment by Wessel93** [comment]
Deferred
