### ISSUE TITLE
[Small Ticket] Fix topic names

### ISSUE THREAD

**Issue by Wessel93** [rodekruis/social-media-listening#128]
- [x] Share list of topics needed in Argilla
- [x] Fix topic names in pipeline & model
- [ ] Fix topic names retroactively in Argilla

**Comment by Wessel93** [comment]
OTHER PROGRAMS/OTHER NGOS
RC CONNECT WITH THE RED CROSS
RC PROGRAM INFORMATION
RC PMER/NEW PROGRAM OPPORTUNITIES
TRANSPORT/MOVEMENT
CVA PROGRAM INFO
CVA REGISTRATION
CVA INCLUSION
CVA PAYMENT
CVA PMER
SHELTER
FOOD
NFI
HEALTH
WASH
PSS & RFL
LEGAL
WORK/JOBS
EDUCATION
CHILDREN
TRANSLATION/LANGUAGE
CAR
MONEY/BANKING
GOODS & SERVICES
PARCEL
PETS
CONNECTIVITY
ARMY
SENTIMENT
ANOMALY

**Comment by Wessel93** [comment]
@EKlochkova do you still need to review this list?

**Comment by EKlochkova** [comment]
This is a complete list.

**Comment by jmargutt** [comment]
Pipeline and model updated, now we need to fix retroactively the data that is already `in` argilla. Loop over all datasets and change label and annotations name from
`topics = [
        "ANOMALY", "ARMY", "CHILDREN", "CONNECTIVITY", "CONNECTWITHREDCROSS", "EDUCATION", "FOOD", "GOODSSERVICES",
        "HEALTH", "INCLUSIONCVA", "LEGAL", "MONEY/BANKING", "NFINONFOODITEMS", "OTHERPROGRAMSOTHERNGOS", "PARCEL",
        "PAYMENTCVA", "PETS", "PMER/NEWPROGRAMOPERTUNITIES", "PROGRAMINFO", "PROGRAMINFORMATION", "PSSRFL",
        "REGISTRATIONCVA", "SENTIMENT/FEEDBACK", "SHELTER", "TRANSLATION/LANGUAGE", "TRANSPORT/CAR",
        "TRANSPORT/MOVEMENT", "WASH", "WORK/JOBS"
    ]`
to 
`topics = [
        "ANOMALY", "ARMY", "CHILDREN", "CONNECTIVITY", "RC CONNECT WITH RED CROSS", "EDUCATION", "FOOD", "GOODS/SERVICES",
        "HEALTH", "CVA INCLUSION", "LEGAL", "MONEY/BANKING", "NFI", "OTHER PROGRAMS/NGOS", "PARCEL",
        "CVA PAYMENT", "PETS", "RC PMER/NEW PROGRAMS", "CVA PROGRAM INFO", "RC PROGRAM INFO", "PSS & RFL",
        "CVA REGISTRATION", "SENTIMENT", "SHELTER", "TRANSLATION/LANGUAGE", "CAR",
        "TRANSPORT/MOVEMENT", "WASH", "WORK/JOBS"
    ]`

**Comment by EKlochkova** [comment]
We miss one label in Argilla - CVA PMER

**Comment by jmargutt** [comment]
added CVA PMER
