### ISSUE TITLE
[Task] Migrate to new pipeline

### ISSUE THREAD

**Issue by jmargutt** [rodekruis/social-media-listening#144]
- [x] Clone Argilla VM.
- [x] Test locally that new/refactored pipeline works and correctly pushes to cloned Argilla VM.
- [x] Create scripts to run new pipeline for each country, and push to cloned Argilla VM.
- [x] Create new logic apps to run new pipeline for each country (or is there a smarter way?).
- [x] Set scraping day to TUESDAY, to avoid getting banned (cannot run two scrapes at the same time).
- [x] Verify in next scrape (4-5 March) that pipeline runs and data is in the cloned Argilla VM.
- [x] Delete old logic apps and make the new pipeline point to production Argilla VM.

**Comment by jmargutt** [comment]
- New VM [sml-argilla-vm-dev](https://portal.azure.com/#@rodekruis.onmicrosoft.com/resource/subscriptions/b2d243bd-7fab-4a8a-8261-a725ee0e3b47/resourceGroups/510_Ukraine_Response_Digital_CEA/providers/Microsoft.Compute/virtualMachines/sml-argilla-vm-dev/overview)
- URL: http://52.166.251.117
- Credentials same as sml-argilla-vm

**Comment by p-phung** [comment]
- [ ] Define `Context()` to fit country settings
- [ ] Update `push_to_argilla()` to the `smm`'s latest commit @Wessel93 
- [ ] if we decide to continue with docker for CICD, find way to optimise docker+poetry to reduce image size (it is currently 13GB). See [best practices](https://github.com/orgs/python-poetry/discussions/1879#discussioncomment-2469844), [multistages build](https://medium.com/vantageai/how-to-make-your-python-docker-images-secure-fast-small-b3a6870373a0)

**Comment by p-phung** [comment]
[Latest commit](https://github.com/rodekruis/social-media-listening/commit/d23aeeabcce04a98f560aa4fcc90a7c880cf75a4) is successfully tested.

Docker image for the new pipeline is pushed to Azure CR. Image name: `social-media-listening`. A github workflow is set to push new updates to ACR whenever push is made.

New logic apps per country are set. Their start time is as following: 
- Bulgaria: 1AM
- Poland: 2 AM
- Slovakia: 3 AM
- Ukraine: 4 AM

Notes:
- The image is still heavy, like 11.3 GB. I think it is not a top priority now. But we can consider to minimise it when needed. See my comment above.
- We still need to work on the `Context()`?
- We still need to work a bit on the code for reading Azure secrets. Atm, the code looks for secrets variables name (e.g. `API_HASH`, `API_ID`), not Azure secret name (`telegram-secrets`).

**Comment by jmargutt** [comment]
@p-phung I'll add a new issues for the open points, let's finish the test with whatever we have
