### ISSUE TITLE
[Small Ticket] Load class is test-ready

### ISSUE THREAD

**Issue by jmargutt** [rodekruis/social-media-listening#27]
### **Who requested this small ticket?**
Wessel.

### **What needs to be done?**
- [ ] Complete refactoring of Load class
- [ ] Create a new SQL database instance in Azure

**Comment by Wessel93** [comment]
@jmargutt and @p-phung here a list orf all the TODO in the code to give an overview of what needs to be done:

- Finalize save_messages function by:
1. Finalize when storage is Azure SQL Database. I think this is mostly a copy paste from old code
2. Same when storage is Azure Blob storage. Again a copy paste mostly, all helper functions are already there

- Save word frequencies function -> low priority, only needs to be saved locally

- Finalize get_messages for all storage types -> same as save_messages, mostly a copy paste form old code

- Connection with sql database -> This one is more work.
1. First step is to set up a azure sql table that contains all the fields as defined in message class
2. Then some Minor TODO's as specified in code
3. Set new table name in read_db function
4. Align _prepare_messages_for_db function to fields in message class
5. Need to test writing and reading
