### ISSUE TITLE
[Small Ticket] Text Extract class

### ISSUE THREAD

**Issue by jmargutt** [rodekruis/social-media-listening#28]
### **Who requested this small ticket?**
Phuoc.

### **What needs to be done?**
- [ ] Extract class is tested with Telegram

### **Additional context**

**Comment by p-phung** [comment]
I've been trying to get a new number many times for testing the extract unit but all was banned like immediately
so far the scraping works well but not able to map a message to a Message object

Todo next:
- test mapping a message to a Message object

**Comment by p-phung** [comment]
Relevant commits:
-70e899dcc6ad0449e38b99186075c04ea262fbfe
- a4844f2c1c7faa76afb8410e549d8c3704a31da6
- 8fe81ccfbd1c16eb5910e2c56f7f36730547d6a1
- 4f5ef73566aac752903bb3e762db9ad7fbd81d56
