### ISSUE TITLE
[Small Ticket] Set up SML model for Hungary

### ISSUE THREAD

**Issue by 510stefania** [rodekruis/social-media-listening#37]
Hungarian Telegram groups to start with and be implemented in current scrape 17

- [https://t.me/naym_hungary](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2Fnaym_hungary&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=skfwkPH78F8fk73u4K%2FyW9rsH%2BAOds78eYYbprm2mkU%3D&reserved=0)
- [https://t.me/Dopomoga_Hungary_Chat](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2FDopomoga_Hungary_Chat&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U2QupGo36aU8iZcrHJNwgBGrAua0Wgm7YTpD9LMVQdc%3D&reserved=0)
- [https://t.me/helpinhungary](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2Fhelpinhungary&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SQ4O%2FTnF8b%2Fso1qi4y9euejf%2BerKTRRmo%2FAZO%2B2Cxzs%3D&reserved=0)
- [https://t.me/hungaryua](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2Fhungaryua&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IlBkGZkEHF4j9zUX8a7sUWAC6AS4ZkopmHzat7%2BQhBU%3D&reserved=0)
- [https://t.me/HUvolunteerswithUA](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2FHUvolunteerswithUA&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hUODijQT%2B8Z8P2BsF6hRvd9zJhtA7H%2BaghsHQwMFT7E%3D&reserved=0)
- [https://t.me/ukraine_hungary_chat](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2Fukraine_hungary_chat&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mZg0SYOOVVRBHXkThvOQ5szuF5M5nYjTDkbsy3Hb%2F68%3D&reserved=0)
- [https://t.me/+0kqrqTHtTOMyYzdi?fbclid=IwAR2IY4dmvAzA-vy2f7vzFqRHCpMfsT887Es9WqYsS6idNYIeF1jkd5F_oy4](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2F%2B0kqrqTHtTOMyYzdi%3Ffbclid%3DIwAR2IY4dmvAzA-vy2f7vzFqRHCpMfsT887Es9WqYsS6idNYIeF1jkd5F_oy4&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lbcKDUVu2lWW2qOH0%2BXTWE%2BAGObKPP4iFJAmovytOAc%3D&reserved=0)
- [https://t.me/hungary_ua](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2Fhungary_ua&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Os511otry8kIt7qFvztn6G4jWU%2BLPc7OPgU95jnulLg%3D&reserved=0)
- [https://t.me/dopomoga_hungary](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ft.me%2Fdopomoga_hungary&data=05%7C01%7Csmarcuzzi%40rodekruis.nl%7C0e45b044cc974b6dcfaa08db9f2df49e%7Cd3ab97906ae24bd8aa5e02864483e7c7%7C0%7C0%7C638278791957211289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fl0Bsb7UxNncmYfcVOVUu6rA9w1KLYDmqkhqb75nwNA%3D&reserved=0)

**Comment by jmargutt** [comment]
Hungary is set up, will test today at 17:20
