### ISSUE TITLE
[Small Ticket] Hungary capacity

### ISSUE THREAD

**Issue by 510stefania** [rodekruis/social-media-listening#39]
### **Who requested this small ticket?**
HCD: Stefania
TPC: Lars 

### **What needs to be done?**
- [x] Request Lars call/meeting
- [x] Update SML capacity for bi-weekly deliverables
- [x] Teams updates 

### **Additional context**
Add any other context or screenshots about the small ticket here.

**Comment by LarsRedCross** [comment]
Hi! @510stefania  I got a message that I was assigned to this but I do not know what is expected of me. So I am unassigning until clear what is needed from me.

**Comment by 510stefania** [comment]
Hey @Stevens, ***@***.***>
how you doing?

In a nutshell: Hungary required and gave green light to SML service. This of course affects the current capacity planning in terms of hours so budget.
Basically we need to add hours to HCD in the Deliverable phase.
Data should be ok with the allocated hours.

All updates are in the SML team - convo ***@***.***/1692611076292?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=2492220b-d202-49a2-a5dd-0ecaddb154dc&parentMessageId=1692611076292&teamName=510%20-%20SML&channelName=SML%20-%20Ukraine%20Emergency%20Appeal&createdTime=1692611076292&allowXTenantAccess=false> - where I asked you a call/meeting to do the above.

This week I am pretty flexible, calendar up to date, so feel free to schedule 30min for this.
Thanks a lot

Stefania Marcuzzi
510 Strategic Product Designer Consultant
+33 6 37 88 64 42
________________________________
