### ISSUE TITLE
[Process improvement] Round 1: WF, Cleaning data, web app

### ISSUE THREAD

**Issue by 510stefania** [rodekruis/social-media-listening#55]
HCD/Design session done this past Monday. [Miro board here ](https://miro.com/app/board/uXjVMsMYKuo=/?share_link_id=969563916573)

Today we moved forward with Jacopo and we prioritized tasks  as follow:

- [ ] Fix translations & member count issue #54 
- [x] Add words and count per category to WF
- [x] Add category "NEW" for unclassified words
- [x] Remove “stop-words” from WF (see comments)
- [x] Data cleaning in messages (less than 10 characters, duplicates)
- [x] SML UI: automatically set dates
- [x] SML UI: select more than one country at the time

Consolidate data in an aggregated file TBD when all the above will be done

**Comment by 510stefania** [comment]
RE [stopwords](https://www.ranks.nl/stopwords):

- [ ] Default English stopwords list : yes please but we need to keep the following words that we categorize - you can add to the model - as questions:
how
how's
what
what's
when
when's
where
where's
which
while
who
who's
whom
why
why's

- [ ] MySQL Stopwords: yes please but we need to keep (and you can add into model):

appropriate (feedback)
available (could be shelter or UN/program)
fifth (payment)
how (question)
needs (need)
next (payment)
own (shelter / good services)
who's (question)
why (question)
near (location)
apart (RFL / humans)
awfully (feedback)
five (payment)
second (payment)
came (movement)
eight (payment)
help (need)
last (payment)
looking (shelter / good services)
name (admin/registration)
two (payments)
where's (question)
whom (question)
wish (need)
wonder (question)
need (need)
sent (parcel)

- [ ] Google History: yes please

- [ ] Long Stopword List: yes please but we need to keep (and you can add):
across (question)
available (UN rpogram)
beginning (time)
begins / begin (Un program)
came (movement)
edu (education)
end - ending (UN program)
home (sheleter)
once, one, two, twice and all sort of numbers (payment)
promptly (question - they use promt)
sent (parcel)
stop (movement)
suggest (question)
tell (question)
un (UN other program)
went (movement)
what where the 5W + how (question)
wish (need)

** IMPORTANT: 

- [ ] Could you pls add both in WF and messages the different translations of Red Cross?
CC
QC
RC
KR Krest
Krest
Criminal Code
KK


Now that I think of... could we add list like cities and program names? That would classify quite a lot!

**Comment by jmargutt** [comment]
@510stefania about stopwords: please share ONE list with the words that need to be removed and open a new issue if we need to change the WF classification

**Comment by 510stefania** [comment]
Stopwords to keep with related category [here](https://rodekruis.sharepoint.com/sites/SmlVK-510/_layouts/15/guestaccess.aspx?share=EeUbO01PDihFkreKhQcnfvMBu7gEa_S1bTaF4Bhm9A56aw&e=K7CKLH)
I also add some keywords for the RC @jmargutt

**Comment by 510stefania** [comment]
reviewed very quickly the above with @p-phung.
@jmargutt we need to schedule a call for feedbacks on the process and the implementations.

Next actions:

- [ ] Laktchih to consilidate WF adjustment in 1 file
- [ ] member count not correct : @p-phung & @jmargutt need to check what is wrong and possibly fix it before S20 (starts monday). If not, Monday/Tuesday 1 DS has to set up workaround (pivot table) for HCD.

**Comment by p-phung** [comment]
@510stefania I suggest a separate task for the member count issue. So that we can keep track and clean tasks.

I just made one for the issue here https://github.com/orgs/rodekruis/projects/4?pane=issue&itemId=39790081

**Comment by p-phung** [comment]
I will pick the task up later this week FYI and follow up with you next week about the backup plan (pivotting)

**Comment by 510stefania** [comment]
[like]  Stefania Marcuzzi reacted to your message:
________________________________

**Comment by 510stefania** [comment]
@jmargutt can we go through feedbacks tomorrow during standup with Laktchih?

**Comment by 510stefania** [comment]
Link to stopwords [here](https://rodekruis.sharepoint.com/sites/SmlVK-510/_layouts/15/guestaccess.aspx?share=EeUbO01PDihFkreKhQcnfvMBu7gEa_S1bTaF4Bhm9A56aw&e=3KeYTZ) @jmargutt

**Comment by jmargutt** [comment]
implemented
