### ISSUE TITLE
Message counting is no longer correct

### ISSUE THREAD

**Issue by p-phung** [rodekruis/social-media-listening#58]
__Issue found:__
- HCD reports that the number of messages count per channel in the member count files
- Number of messages counted in country messages files are less, and even way less than the counts in the member count files

__Consequences:__
- HCD team uses these numbers to determine number of messages to be read and reported in the factsheets
- The numbers are off and they need to spend time to calculate manually

__What need to be done:__
- [x] Check how and when the counting is done in the code atm.
- [ ] If it is shown that the issue is in the script, fix it - so that the new counts can be done in the coming scrape 2nd Oct
- [ ] If the issue is not from the script or no solution comes up before the coming scrape - show HCD team how to count messages using Excel's pivot

**Comment by 510stefania** [comment]
@p-phung any update in this issue? Thanks

**Comment by p-phung** [comment]
@510stefania I didn't make time to work on it on Friday. I'll be available to help you with the new counting

**Comment by 510stefania** [comment]
@p-phung FYI in S20 the member count is not correct.

**Comment by p-phung** [comment]
@510stefania I am aware of that, see my comment last week (right above yours). Ping me if you need my help to do the counting

**Comment by p-phung** [comment]
@510stefania I just dived into this issue. This causes by the time difference in scraping and classifying:
- we scrape messages for a country at specific time e.g. 13:00 Monday from 13:00 of Monday 2 weeks before to 13:00 of Monday now. The data is then push to the database
- In the scraping process, we collect info of members counts and number of _scraped_ messages
- we then classify the messages of that countries by pulling the data from the database by selecting dates. We only specify dates to pull the data, not specify the time. That excludes some data on the last scraping date.
- because of this, there shall always be discrepancy between number of scraped messages and processed messages (translated, classified).

Which number do you prefer to report in the factsheet: scraped messages or processed messages?

For the latter, we can add the counting in the classification to count number of processed messages, besides the number of scraped messages (which go together with the member count).

**Comment by p-phung** [comment]
@510stefania @EKlochkova 
we agree to count number of messages classified. We add the count in the classification and export the count csv file to share with CEA team.

**Comment by jmargutt** [comment]
should be solved now, moving to review to confirm in the next scrape

**Comment by Stef510** [comment]
HCD to verify S25 and provide feedback
