### ISSUE TITLE
[Capacity] Hour request for Lakchih

### ISSUE THREAD

**Issue by 510stefania** [rodekruis/social-media-listening#69]
Allocate to Lakchih 5 days of work (40h) for the task [T22602 - SML User Research](https://app.forecast.it/T22602). (Oct-Nov) as he's helping with the user research.

**Comment by pimkemperman** [comment]
@510stefania , I allocated Lakchih to the task for User Research. Can you confirm with him that he writes his work for user reserach on this task?
https://app.forecast.it/project/P-495/scoping/T22602

**Comment by 510stefania** [comment]
[like]  Stefania Marcuzzi reacted to your message:
________________________________

**Comment by 510stefania** [comment]
[like]  Stefania Marcuzzi reacted to your message:
________________________________
