### ISSUE TITLE
[Meeting] Reserve room for hackathon

### ISSUE THREAD

**Issue by 510stefania** [rodekruis/social-media-listening#72]
Would be grateful if you can reserve a room for our hackathon, Thu 9-17.
Thanks

**Comment by jmargutt** [comment]
Hierbij bevestigen wij uw reservering.
--
 
Onderwerp: | SML hackathon
Vanaf : | 19-10-2023 09:00
Tot: | 19-10-2023 14:00
Ruimte: | Ruimte 0.18 Solferino
